baseURL = "https://unejournee.laliberte.ch/"
languageCode = "fr-ch"
title = "La Liberté - Une journée de Liberté"
theme = "laliberte"

[params]
  timelineTitle = "La timeline de la Liberté"
  circulateNavigationTitle = 'Poursuivre la lecture'
  aboutPageTitle = 'À propos'
  aboutPageSlug = 'a-propos'
  videoActionLabel = 'Voir le reportage'

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true