baseURL = "https://laliberte150.staging.antistatique.net/"
languageCode = "fr-ch"
title = "La Liberté a 150 ans"
theme = "laliberte-hugo-theme"

[params]
  timelineTitle = "La timeline de la Liberté"
  circulateNavigationTitle = 'Poursuivre la lecture'
  aboutPageTitle = 'À propos'
  aboutPageSlug = 'a-propos'
  videoActionLabel = 'Voir le reportage'

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true