baseURL = "https://unejournee.lalib.ch/"
languageCode = "fr-ch"
title = "La Liberté - Une journée de Liberté"
theme = "laliberte"

[params]
  timelineTitle = "Une journée de Liberté"
  circulateNavigationTitle = 'Poursuivre la lecture'
  aboutPageTitle = 'À propos'
  aboutPageSlug = 'a-propos'
  videoActionLabel = 'Voir le portrait vidéo'
  footerRight = "Tous droits réservés"
  Plausible = 'unejournee.lalib.ch'

[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true
